
services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boarding_house
    ports:
      - "3307:3306"
  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6380:6379"
